=== CyFI-Lab-Public/RetroScope/external/apache-harmony/support/src/test/resources/config/excludes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    xmlns="http://incubator.apache.org/harmony/testing" 
	    targetNamespace="http://incubator.apache.org/harmony/testing">

  <!--
  * A suite contains zero or more type declarations 
  -->
  <xsd:element name="suite">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="type" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!--
  * A type contains one or more exclude elements.
  * A type has a single attribute (id) which can be
  * any meaningful character value that is based on
  * proper XML naming conventions (must begin with a 
  * letter or underscore).
  -->
  <xsd:element name="type">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="exclude" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="idtype" use="required" />
    </xsd:complexType>
  </xsd:element>

  <!--
  * An exclude element can have an optional reason
  * element. 
  -->
  <xsd:element name="exclude">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="reason" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="idtype"  default="all" />
      <xsd:attribute name="platform" type="platformlisttype" default="all" />
      <xsd:attribute name="shouldfix" type="booleanstringtype" default="true" />
    </xsd:complexType>
  </xsd:element>

<!--
  * A reason element has no attributes, only parsed
  * character data.	
  -->
  <xsd:element name="reason">
    <xsd:complexType mixed="true"/>
  </xsd:element>

 
  <!--
  * Type idtype is any string data.
  -->
  <xsd:simpleType name="idtype">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  

  <!--
  * Type platformstringtype is one of the 
  * strings "all", "win.IA32" or "linux.IA32".
  -->
  <xsd:simpleType name="platformstringtype" >
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="win.IA32"/>
      <xsd:enumeration value="linux.IA32"/>
      <xsd:enumeration value="all"/>
    </xsd:restriction>
  </xsd:simpleType>


  <xsd:simpleType name="platformlisttype">
    <xsd:list itemType="platformstringtype"/>
  </xsd:simpleType>


  <!--
  * Type booleanstringtype is one of the 
  * strings "true" or "false".
  -->
  <xsd:simpleType name="booleanstringtype" >
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="true"/>
      <xsd:enumeration value="false"/>
    </xsd:restriction>
  </xsd:simpleType>
  
</xsd:schema>

=== CyFI-Lab-Public/RetroScope/external/apache-harmony/support/src/test/resources/config/jcltest-excludes.xml
<?xml version="1.0" encoding="UTF-8"?>
<hy:suite xmlns:hy="http://incubator.apache.org/harmony/testing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://incubator.apache.org/harmony/testing excludes.xsd">

	<!-- Applet module test exclusions -->


	<!-- Archive module test exclusions -->
	<hy:type id="tests.api.java.util.zip.GZIPInputStreamTest">
        <hy:exclude id="test_read$BII" shouldfix="true">
            <hy:reason>java.io.IOException: Size mismatch</hy:reason>
        </hy:exclude>
        <hy:exclude id="test_close" shouldfix="true">
            <hy:reason>java.io.IOException: Size mismatch</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.util.zip.InflaterInputStreamTest">
        <hy:exclude id="test_ConstructorLjava_io_InputStream" shouldfix="true">
            <hy:reason>read() threw an exception while testing constructor</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.util.zip.InflaterTest">
        <hy:exclude id="test_setDictionary$B" shouldfix="true">
            <hy:reason>java.lang.IllegalArgumentException in native method</hy:reason>
        </hy:exclude>
    </hy:type>
    
    
    <!-- Auth module test exclusions -->
    <hy:type id="javax.security.auth.login.serialization.SerAccountExpiredExceptionTest">
        <hy:exclude id="testGolden" shouldfix="true">
            <hy:reason>java.io.EOFException</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="javax.security.auth.login.serialization.SerCredentialExpiredExceptionTest">
        <hy:exclude id="testGolden" shouldfix="true">
            <hy:reason>java.io.EOFException</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="javax.security.auth.x500.X500PrincipalTest">
        <hy:exclude id="testValidEncoding" shouldfix="true">
            <hy:reason>Undiagnosed Error</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.javax.security.auth.x500.X500PrincipalTest">
        <hy:exclude id="all" shouldfix="true">
            <hy:reason>Undiagnosed Error</hy:reason>
        </hy:exclude>
    </hy:type>
    

	<!-- AWT module test exclusions -->
	
	
	<!-- Beans module test exclusions -->
	<hy:type id="java.beans.beancontext.BeanContextServicesSupportTest">
        <hy:exclude id="all" shouldfix="true">
            <hy:reason>protected system package 'java.beans.beancontext'</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="java.beans.beancontext.BeanContextSupportTest">
        <hy:exclude id="all" shouldfix="true">
            <hy:reason>protected system package 'java.beans.beancontext'</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="org.apache.harmony.tests.java.beans.BeansTest">
        <hy:exclude id="testLoadBySpecificClassLoader" shouldfix="true">
            <hy:reason>Class with name org.apache.harmony.tests.beans.auxiliary.SampleBean is not found</hy:reason>
        </hy:exclude>
        <hy:exclude id="testLoadByDefaultClassLoader" shouldfix="true">
            <hy:reason>Class with name org.apache.harmony.tests.beans.auxiliary.SampleBean is not found</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="org.apache.harmony.tests.java.beans.EventHandlerTest">
        <hy:exclude id="testNullListenerMethodName" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInvoke" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInvokeWithNullPropertyName" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testCreateWithDottedParameterCall" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testCreateWithMethodCallWhichIsSetter" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testCreateForStaticMethodAsPropertyGetter" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="org.apache.harmony.tests.java.beans.SimpleBeanInfoTest">
        <hy:exclude id="testLoadImage" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.beans.BeanDescriptorTest">
        <hy:exclude id="testBeanDescriptorClass" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testBeanDescriptorClassClass_CustomizerClassNull" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.beans.BeansTest">
        <hy:exclude id="testInstantiateClassLoaderString_Class" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiateClassLoaderString_Ser" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiateClassLoaderStringBeanContext_Class" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiateClassLoaderStringBeanContext_Ser" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiateClassLoaderStringBeanContextAppletInitializer_Class" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiateClassLoaderStringBeanContextAppletInitializer_Ser" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testIsInstanceOf_BeanNull" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.beans.CustomizedPersistenceDelegateTest">
        <hy:exclude id="testArrayPD" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testProxyPD" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testPrimitivePD" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testMethodPD" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testFieldPD" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.beans.DefaultPersistenceDelegateTest">
        <hy:exclude id="testInstantiate_NullProperty" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_EmptyProperty" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_NonExistingGetter" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_NonExistingGetterNulEncoder" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_InitialUpperCasePropName" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_NoGetter" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInstantiate_NotRegularGetter" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testMutatesTo_NormalNoProperty" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testMutatesTo_NormalWithEmptyPropertyPublicEqualMethod" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testMutatesTo_Null" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_Normal" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_NormalBeanInfo" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_SameInstance" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_TransientProperty" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_NullClass" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_NullInstances" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_NullEncoder" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testInitialize_NotRegularGetter" shouldfix="true">
            <hy:reason>Undiagnosed error</hy:reason>
        </hy:exclude>
    </hy:type>
    
    <hy:type id="tests.api.java.beans.EncoderTest">
        <hy:exclude id="testGetExceptionListener" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
        </hy:exclude>
        <hy:exclude id="testSetExceptionListener_Null" shouldfix="true">
            <hy:reason>Undiagnosed failure</hy:reason>
